# Optional parameters go here!
variable "name" {
  description = "Name of the serverless cache. If null, will default to product."
  default     = null
  type        = string
}

variable "create" {
  description = "Determines whether serverless cache resource will be created."
  type        = bool
  default     = true
}

variable "engine" {
  description = "Name of the cache engine to be used for this serverless cache. Valid values are `memcached` or `redis`."
  type        = string
  default     = "redis"
  validation {
    condition     = contains(["redis", "memcached"], var.engine)
    error_message = "The engine variable must be one of [redis, memcached]."
  }
}

variable "cache_usage_limits" {
  description = "Sets the cache usage limits for storage and ElastiCache Processing Units for the cache."
  type        = map(any)
  default     = {}
}

variable "daily_snapshot_time" {
  description = "The daily time that snapshots will be created from the new serverless cache. Only supported for engine type `redis`."
  type        = string
  default     = null
}

variable "description" {
  description = "User-created description for the serverless cache. If null, defaults to 'Serverless Cache for <name>'."
  type        = string
  default     = null
}

variable "kms_key_id" {
  description = "ARN of the customer managed key for encrypting the data at rest. If no KMS key is provided, a default service key is used."
  type        = string
  default     = null
}

variable "major_engine_version" {
  description = "The version of the cache engine that will be used to create the serverless cache."
  type        = string
  default     = null
}

variable "security_group_ids" {
  description = "One or more VPC security groups associated with the serverless cache. If null, a security group will be created by this module."
  type        = list(string)
  default     = null
}

variable "snapshot_arns_to_restore" {
  description = "The list of ARN(s) of the snapshot that the new serverless cache will be created from. Available for Redis only."
  type        = list(string)
  default     = null
}

variable "snapshot_retention_limit" {
  description = "(Redis only) The number of snapshots that will be retained for the serverless cache that is being created."
  type        = number
  default     = null
}

variable "subnet_ids" {
  description = "A list of the identifiers of the subnets where the VPC endpoint for the serverless cache will be deployed. If null, a list will be generated by looking up subnets in the resolved VPC."
  type        = list(string)
  default     = null
}

variable "vpc_id" {
  description = "VPC ID to create resources in. If null, one will be guessed based on `vpc_data_lookup_tags`."
  default     = null
  type        = string
}

variable "vpc_data_lookup_tags" {
  description = "Value of the `tags` parameter in the `aws_vpc` data source used in this module. If null, a dynamic lookup based on `environment` will be used. Ignored if `vpc_id` is populated."
  default     = null
  type        = map(string)
}

variable "subnet_data_lookup_filters" {
  description = "Values of the `filter` blocks in the `aws_subnets` data source used in this module. If null, one will be guessed using the resolved VPC and a `Name` filter of `*-private-*`. Ignored if `subnet_ids` is populated."
  default     = null
  type        = map(any)
}

variable "use_prefix" {
  description = "Whether to use prefixes in the resource names. If false, will use a fully specified name for resources."
  default     = true
  type        = bool
}

variable "sg_name" {
  description = "Name of the security group to be created. If null, will use the name of the cache."
  default     = null
  type        = string
}

variable "ingress_cidr_blocks" {
  description = "List of CIDR blocks to allow ingress from. If null, `ingress_source_sg_id` must be used."
  default     = null
  type        = list(string)
}

variable "ingress_source_sg_id" {
  description = "Security group ID to allow ingress from. If null, `ingress_cidr_blocks` must be used."
  default     = null
  type        = string
}

variable "user_group_id" {
  description = "The identifier of the UserGroup to be associated with the serverless cache. Available for Redis only."
  type        = string
  default     = null
}

variable "timeouts" {
  description = "Define maximum timeout for creating, updating, and deleting serverless cache resources."
  type        = map(string)
  default     = {}
}
